# golangci-lint v2 configuration for face recognition CLI
# Run: golangci-lint run ./...

version: "2"

run:
  timeout: 5m
  go: "1.21"
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - file

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - face

linters:
  default: standard
  enable:
    # Additional recommended linters
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - tparallel
    - unconvert
    - unparam
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 17

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - hugeParam

    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck)
        - G115  # Integer overflow in test files (safe for image processing)
        - G301  # Directory permissions 0755 is acceptable for CLI
        - G304  # File path from variable (intentional for CLI)
        - G306  # WriteFile permissions (cascade file needs read access)

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      for-loops: true

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: var-naming

    dupl:
      threshold: 150

    exhaustive:
      default-signifies-exhaustive: true

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      # Test files can have longer functions and magic numbers
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gocyclo

      # Main and cmd can have init functions
      - path: (main|cmd/)\.go
        linters:
          - gochecknoinits

      # Allow dot imports in tests
      - path: _test\.go
        text: "dot-imports"

      # Ignore error check for Close() calls
      - linters:
          - errcheck
        text: "Error return value of .*(Close|Remove)"

    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error